/**
 * pin-lock.js
 * Gatekeeper screen shown before the site is revealed.
 * PIN is set in /config/settings.js — do not edit this file.
 *
 * Deliberately has zero dependencies on config.js/OCEAN so it can never be
 * blocked by anything else failing to load — the lock always works.
 */
(function (window, document) {
  'use strict';

  // PIN comes from config/settings.js (loaded before this file in index.html)
  var PIN_VALUE = String(window.WEBSITE_PIN || '0000');
  var PIN_LENGTH = Math.min(6, Math.max(4, PIN_VALUE.length));
  var STORAGE_KEY = 'oceanPinUnlocked';
  var reducedMotion = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  function ready(fn) {
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', fn);
    } else {
      fn();
    }
  }

  ready(function init() {
    var lock = document.getElementById('pinLock');
    if (!lock) return;

    // Already unlocked earlier this session — skip straight to the site.
    try {
      if (window.sessionStorage && sessionStorage.getItem(STORAGE_KEY) === '1') {
        lock.parentNode && lock.parentNode.removeChild(lock);
        setTimeout(function() { window.dispatchEvent(new Event('pinUnlocked')); }, 500);
        return;
      }
    } catch (e) { /* sessionStorage unavailable — show the lock normally */ }

    var card       = lock.querySelector('.pin-lock__card');
    var digitsWrap = lock.querySelector('.pin-lock__digits');
    var input      = lock.querySelector('.pin-lock__hidden-input');
    var errorEl    = lock.querySelector('.pin-lock__error');
    var form       = lock.querySelector('.pin-lock__form');

    if (!card || !digitsWrap || !input || !form) return;

    input.setAttribute('maxlength', String(PIN_LENGTH));

    // Build digit boxes dynamically from PIN_LENGTH
    var boxes = [];
    for (var i = 0; i < PIN_LENGTH; i++) {
      var box = document.createElement('span');
      box.className = 'pin-digit';
      var dot = document.createElement('span');
      dot.className = 'pin-digit__dot';
      box.appendChild(dot);
      digitsWrap.appendChild(box);
      boxes.push(box);
    }

    setLocked(true);

    function setLocked(state) {
      document.documentElement.classList.toggle('pin-locked', state);
      var siblings = document.body.children;
      for (var s = 0; s < siblings.length; s++) {
        var el = siblings[s];
        if (el === lock) continue;
        if (state) {
          el.setAttribute('inert', '');
          el.setAttribute('aria-hidden', 'true');
        } else {
          el.removeAttribute('inert');
          el.removeAttribute('aria-hidden');
        }
      }
    }

    function render() {
      var val = input.value;
      boxes.forEach(function (box, idx) {
        box.classList.toggle('is-filled', idx < val.length);
        box.classList.toggle('is-active', idx === val.length);
      });
    }

    function clearError() {
      card.classList.remove('is-error');
      errorEl && errorEl.classList.remove('is-visible');
    }

    function shakeError() {
      clearError();
      input.value = '';
      render();
      void card.offsetWidth;
      card.classList.add('is-error');
      errorEl && errorEl.classList.add('is-visible');

      var onEnd = function () {
        card.classList.remove('is-error');
        card.removeEventListener('animationend', onEnd);
      };
      card.addEventListener('animationend', onEnd);

      setTimeout(function () {
        try { input.focus({ preventScroll: true }); } catch (e) { input.focus(); }
      }, reducedMotion ? 30 : 80);
    }

    function unlock() {
      input.blur();
      card.classList.add('is-success');
      try { sessionStorage.setItem(STORAGE_KEY, '1'); } catch (e) {}

      window.dispatchEvent(new Event('pinUnlocked'));

      var revealDelay = reducedMotion ? 150 : 850;
      setTimeout(function () {
        lock.classList.add('is-unlocked');
        setLocked(false);
        setTimeout(function () {
          if (lock.parentNode) lock.parentNode.removeChild(lock);
        }, reducedMotion ? 0 : 850);
      }, revealDelay);
    }

    function attemptUnlock() {
      var val = input.value.replace(/\D/g, '');
      if (val.length !== PIN_LENGTH || val !== PIN_VALUE) {
        shakeError();
        return;
      }
      unlock();
    }

    input.addEventListener('input', function () {
      input.value = input.value.replace(/\D/g, '').slice(0, PIN_LENGTH);
      clearError();
      render();
      if (input.value.length === PIN_LENGTH) attemptUnlock();
    });

    form.addEventListener('submit', function (e) {
      e.preventDefault();
      attemptUnlock();
    });

    lock.addEventListener('pointerdown', function (e) {
      if (!card.contains(e.target) || e.target === card) {
        input.focus({ preventScroll: true });
      }
    });

    render();
    setTimeout(function () {
      try { input.focus({ preventScroll: true }); } catch (e) {}
    }, reducedMotion ? 0 : 450);
  });
})(window, document);
